### ISSUE TITLE
[52] 문제의 글자 수 UI

### ISSUE THREAD

**Issue by changgunyee** [connect-foundation/2019-15#10]
- [x] 캔버스 위에 정답의 글자 수를 띄운다.
- [x] 일정 시간이 지나면(제한시간의 1/4이 남은 시점) 단어 중 한 글자를 공개한다.
- [x] 출제자는 선택한 단어를 띄운다.

**Comment by Einere** [comment]
https://github.com/connect-foundation/2019-15/pull/176
