### ISSUE TITLE
[BUG] 친구 닉네임 안적어도 삭제 화면창이 뜨는 문제

### ISSUE THREAD

**Issue by kkw01234** [connect-foundation/2019-15#222]
![](https://user-images.githubusercontent.com/44748071/70300160-20761200-183a-11ea-9a14-e6c142ac0850.jpg)

**Comment by hos101010** [comment]
흑흑흑 재연을 못하겠네요 더 시도해보겠습니다! 에러 찾아주셔서 감사해요!!

**Comment by hos101010** [comment]
수정완료!
