### ISSUE TITLE
[BUG] 로그아웃 실패

### ISSUE THREAD

**Issue by NBJ1995** [connect-foundation/2019-15#226]
**Describe the bug**
게임을 즐기다 방밖으로 나가졌는데 그상태에서 로그아웃 하려고했었으나
![image](https://user-images.githubusercontent.com/37498859/70300878-12c18c00-183c-11ea-96d7-ba2bf381f1d5.png)

**To Reproduce**
1. 게임 즐기다 나가짐
2. 로그아웃함.
3. 펑

**Expected behavior**
로그아웃이 되고 다시 메인화면으로 돌아가야 함

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by hos101010** [comment]
중간에 서버가 터진걸로 보입니다...죄송합니다...ㅜ....
