### ISSUE TITLE
[BUG] 문제를 낸 뒤에 상대방이 그림을 그릴 때 안 보입니다.

### ISSUE THREAD

**Issue by kyujonglee** [connect-foundation/2019-15#227]
**Describe the bug**
상대방이 그리는 그림이 안 보입니다.

**To Reproduce**
1. 제가 문제를 낸 뒤 상대방이 문제를 맞춥니다.
2. 상대방이 그림을 그리는데 저는 안 보입니다.

**Expected behavior**
상대방의 그림이 보여야함.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : chrome

**Comment by Einere** [comment]
#223 중복된 버그
