### ISSUE TITLE
[BUG] 닉네임이 중복되고 썸네일이 가끔 안보여요

### ISSUE THREAD

**Issue by sang-eun** [connect-foundation/2019-15#228]
**Describe the bug**
지각이라는 닉네임의 유저가 두명 있고, 썸네일이 가끔 에러로 보이지 않습니다. 썸네일이 자꾸 바뀌는 것 또한 의도하시는건가요?

**To Reproduce**
1. 방에 들어옴
2. 게임 중에 발생

**Expected behavior**
같은 닉네임의 유저가 존재하지 않고 정상적인 썸네일을 보여줌 

**Screenshots**
![image](https://user-images.githubusercontent.com/19178129/70301377-887a2780-183d-11ea-8133-8a047ea38e8c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by Einere** [comment]
동일한 계정으로 접속한 경우, 정상적인 현상입니다.

**Comment by Einere** [comment]
프로필 사진은 수정할게용

**Comment by Einere** [comment]
#262 수정완료
