### ISSUE TITLE
[BUG] 문제를 맞췄더니 서버가 터진 것 같아요

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-15#230]
거북이라는 닉네임으로 접속됐고, 담배 / 미용실 두문제를 맞췄는데 둘 다 서버가 터졌습니다.!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Einere** [comment]
서버는 다양한 이유로 터지기 때문에, 해당 버그 리포트에 정보가 부족하네요..
