### ISSUE TITLE
[BUG]서버 죽음

### ISSUE THREAD

**Issue by hos101010** [connect-foundation/2019-15#251]
**Describe the bug**

- 2명이 방에 들어간 후 한 사람이 나갔다가 들어오면 서버가 죽음
=> roomState의 isPlayable, isPlaying 문제라고 예상됨
1명 빼고 다 나갔다가 다시 들어오면 나갈때의 로직이 없어서 isPlaying상태를 유지
게임이 시작한 후 다시 1명만 남아 대기 상태가 되면 isPlayable 상태로 변경해줘야함!

- 똑같은 상황에 userlist의 painter가 분홍색이 되어야하는데 안됨
=> 동일한 원인

**Comment by Einere** [comment]
지금 개발중인 로컬에서는 위 해당 사항은 해결되었음.
그러나 문제 선택 도중에 출제자가 나가버리면 게임을 영원히 시작할 수 없는 버그가 있음.
- 출제자가 나간 경우, gamestart를 다시 보내주는 식으로 해결해야 할 듯

**Comment by Einere** [comment]
#259 수정완료
