### ISSUE TITLE
[BUG] 게임 시작했는데 단어 선택 안했을 때 다른 유저가 들어가면 서버 죽음

### ISSUE THREAD

**Issue by hos101010** [connect-foundation/2019-15#254]
**Describe the bug**
isPlaying 상태에서 새로운 유저가 들어오면 지금 하고있는 게임의 제시어를 받는다.
그래서 단어 선택 전에 난입하면 isPlaying상태이나 room.word에 null이 있기 때문에
서버가 죽음

**Comment by Einere** [comment]
#259 에서 수정함.
