### ISSUE TITLE
[BUG] 상단 페이지 명이 이상합니다.

### ISSUE THREAD

**Issue by GirlFriend-Yerin** [connect-foundation/2019-15#271]
**Describe the bug**
홈페이지의 제목이 React App 입니다.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser : chrome
 - Version ?

**Additional context**

**Comment by Einere** [comment]
배포 링크로 접속해보니 정상적으로 나오는게 확인이 되네용.
