### ISSUE TITLE
[BUG] 사진을 지우고 재생을 하니 오류가 뜹니다

### ISSUE THREAD

**Issue by kyujonglee** [connect-foundation/2019-15#273]
**Describe the bug**
사진을 지우고 재생을 하니 오류가 뜸

**To Reproduce**
1. 사진을 지운다
2. 재생을 한다

**Expected behavior**
사진이 없다고 알람창이 뜬다

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Browser [chrome]

**Comment by changgunyee** [comment]
저희 프로젝트가 아닌 거 같습니다!
