### ISSUE TITLE
[BUG] 로그인하지 않고도 main접속이 가능합니다

### ISSUE THREAD

**Issue by sjh2428** [connect-foundation/2019-15#275]
**Describe the bug**
로그인하지 않고도 main접속이 가능합니다

**To Reproduce**
1. URL에 바로 main주소 입력
2. 접속되었습니다

**Expected behavior**
로그인 해달라는 페이지로 가야할 것 같습니다

**Screenshots**
![image](https://user-images.githubusercontent.com/26241585/70773880-04371f80-1dbc-11ea-8086-690f81c3b50f.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 최신

**Additional context**
X

**Comment by hos101010** [comment]
로그인을 안했을 시 로그인 창으로 넘어갑니다!
토큰이 남아있을 수도 있어서 그런걸수도 있는데 혹시 캡처화면이 시크릿모드인가요??

**Comment by sjh2428** [comment]
> 로그인을 안했을 시 로그인 창으로 넘어갑니다!
> 토큰이 남아있을 수도 있어서 그런걸수도 있는데 혹시 캡처화면이 시크릿모드인가요??

지금 다시 해보니 로그인 창으로 잘 넘어가네요.
시크릿모드는 아니였고 Mac OS 다크모드였습니다.
구글 로그인은 했지만 catch my mind에서 로그인하지는 않았었습니다.

**Comment by Einere** [comment]
쿠키가 남아 있는 경우 권한 인증이  됩니다.
쿠키를 지워도 접속이 가능한 건가요?
