### ISSUE TITLE
[BUG]건의사항

### ISSUE THREAD

**Issue by JaeHyeonKim19** [connect-foundation/2019-15#279]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

사람들이 다맞추면 다음문제로 넘어갔으면 좋겠어요! 다시 겜하러갈께요!

**Comment by hos101010** [comment]
한명이라도 못맞추면 기다리고 있고, 다맞추면 넘어갑니다! 혹시 안넘어갔었나요?

**Comment by JaeHyeonKim19** [comment]
음 그때는 다 맞춘걸로 확인했는데 ㅠ 다음에 기회가 되면 정확하게 확인해보겠습니다.

**Comment by hos101010** [comment]
오오오 발견했습니다! 1명 빼고 다 맞췄는데 그 한명이 안맞추고 ㅌㅌ하면 게임이 안끝나네요
버그 발견해줘서 감사합니다아ㅏㅏ

**Comment by Einere** [comment]
구현 완료 #290
머지되면 닫을 예정
