### ISSUE TITLE
[BUG] 단어변경을 여러번 클릭시 에러가 발생하며 더이상 게임이 진행되지 않습니다 

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-15#280]
**Describe the bug**
단어 변경을 세네번 누르니 에러가 발생했습니다 
![image](https://user-images.githubusercontent.com/22452742/70774326-3a28d380-1dbd-11ea-8c94-c3ce801cd876.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hos101010** [comment]
그림 위에 error가 뜨는 거는 단어 db에서 단어를 못받아오는 상황인데
생각하기로는 그 당시에 서버가 죽어서 못받아온 것 같습니다!
혹시 서버가 죽었을일은 없나요??
