### ISSUE TITLE
[BUG] 닉네임 글자 수 제한이 없음

### ISSUE THREAD

**Issue by OriginJang** [connect-foundation/2019-15#281]
**Describe the bug**
- 닉네임 글자 수 제한이 없음

**To Reproduce**
- 방만들기 후 닉네임 입력 시 글자수 제한이 없음

**Expected behavior**
- 적당한 글자수가 필요할듯

**Screenshots**
<img width="1440" alt="스크린샷 2019-12-13 오후 3 32 48" src="https://user-images.githubusercontent.com/30206880/70775455-a35d1680-1dbe-11ea-8e2f-0fa0aa3ef627.png">

**Desktop (please complete the following information):**
- macOS Mojave 10.14.6
- chrome 78.0.3904.108

**Comment by Einere** [comment]
수정 완료 #296
