### ISSUE TITLE
[BUG] 토큰으로 로그인 시, 로그아웃 실패

### ISSUE THREAD

**Issue by changgunyee** [connect-foundation/2019-15#293]
**Describe the bug**
oauth로 로그인하지 않고 토큰으로 바로 로그인 시, back에서 req.user.id를 참조하지 못함으로 생기는 에러. 굳이 `Users.findOne`할 필요 없이 그냥 토큰을 바로 만료시키면 될듯하다

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Einere** [comment]
수정 완료 #298
